version: '3.8' #Docker Compose version

services:
  app:
    build:
      context: .  #Directory with the Dockerfile and source code
      dockerfile: Dockerfile  #Specify the Dockerfile
    ports:
      - "8080:8080" #Map host port 8080 to the container port 8080
    environment:
      - DB_HOST=db #Hostname for the database service
      - DB_USER=postgres #Username for the database service
      - DB_PASSWORD=secret #Password for the database service
      - DB_NAME=items #Name of the database service
    depends_on:
      - db  #Ensures that the database starts up and is running before the app
    networks:
      - app-network #Network to allow communication with the database
    
  db:
    image: postgres:14  #Use the latest official PostgreSQL image
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=items
    ports:
    - "5432:5432" #Maps host port 5432 to the container port 5432
    volumes:
    - postgres-data:/var/lib/postgresql/data  #Persist data in a Docker volume
    networks:
    - app-network

#Define networks for communication between containers
networks:
  app-network:

#Define volumes to persist data
volumes:
  postgres-data: